/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'brand-lime': '#D4F05A',
        'brand-lime-bright': '#D0FA58',
        'brand-lime-dim': '#B5DD3D',
        'brand-lime-dark': '#ADD535',
        'tertiary-container': '#d0cecb',
        'primary-fixed': '#c9f250',
        'primary-container': '#b5dd3d',
        'inverse-on-surface': '#2f312f',
        'surface-variant': '#343534',
        'error': '#ffb4ab',
        'error-container': '#93000a',
        'surface-container': '#1f201f',
        'on-secondary-fixed': '#1c1c1b',
        'on-error': '#690005',
        'surface-container-lowest': '#0d0e0d',
        'surface': '#121413',
        'on-error-container': '#ffdad6',
        'inverse-primary': '#506600',
        'surface-container-low': '#1b1c1b',
        'surface-bright': '#383938',
        'on-primary-fixed': '#161f00',
        'background': '#121413',
        'surface-dim': '#121413',
        'surface-container-high': '#292a29',
        'on-surface-variant': '#C5C9B0',
        'surface-container-highest': '#343534',
        'secondary-fixed-dim': '#c8c6c4',
        'on-background': '#E3E2E0',
        'on-primary-container': '#4a5f00',
        'secondary-container': '#474745',
        'tertiary-fixed-dim': '#c8c6c3',
        'outline': '#8F937C',
        'on-tertiary-fixed': '#1b1c1a',
        'secondary-fixed': '#e5e2e0',
        'outline-variant': '#444936',
        'on-tertiary': '#31302e',
        'primary-fixed-dim': '#add535',
        'on-secondary-container': '#b7b5b3',
        'on-tertiary-fixed-variant': '#474744',
        'on-tertiary-container': '#585855',
        'secondary': '#c8c6c4',
        'primary': '#d0fa58',
        'on-primary-fixed-variant': '#3b4d00',
        'tertiary': '#edeae7',
        'surface-tint': '#add535',
        'on-primary': '#283500',
        'on-secondary-fixed-variant': '#474745',
        'inverse-surface': '#e3e2e0',
        'on-surface': '#E3E2E0',
        'on-secondary': '#31302f',
        'tertiary-fixed': '#e5e2df',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeOut: {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(24px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUpSm: {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        shrinkOut: {
          '0%': { opacity: '1', transform: 'scale(1)' },
          '100%': { opacity: '0', transform: 'scale(0.85)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.92)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        pulse: {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
      },
      animation: {
        fadeIn: 'fadeIn 0.4s ease-out forwards',
        fadeOut: 'fadeOut 0.35s ease-in forwards',
        slideUp: 'slideUp 0.5s ease-out forwards',
        slideUpSm: 'slideUpSm 0.35s ease-out forwards',
        shrinkOut: 'shrinkOut 0.35s ease-in forwards',
        scaleIn: 'scaleIn 0.35s ease-out forwards',
        pulse: 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        shimmer: 'shimmer 1.5s infinite linear',
      },
    },
  },
  plugins: [],
};
